spring:
    application:
        name: "TimeTracking"

    datasource:
        url: jdbc:postgresql://localhost:5432/mydb
        username: myuser
        password: mypass
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
    secret: your-secret-key-here-at-least-256-bits-long-for-HS256
    expiration: 86400000